(function(){'use strict';
const U='https://rlidcatrwonemshwzafp.supabase.co',K='sb_publishable_ocJhWyfPg9rVhYROn_Vj0Q_DSSgxeuE',ADMIN='junjharsingh740@gmail.com',API=U+'/functions/v1/admin-hr-management';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function box(){if($('siteReports'))return;const s=document.createElement('section');s.id='siteReports';s.className='box';s.innerHTML='<div class="report-head"><div><span class="badge">SITE REPORTS & HEALTH</span><h2>Website Overview</h2><p>Live counts and site health from the admin panel.</p></div><button id="refreshReports" class="secondary">↻ Refresh</button></div><div class="report-grid"><article><span>📈</span><b id="rTraffic">—</b><small>Daily Traffic</small></article><article><span>💼</span><b id="rJobs">—</b><small>New Jobs Today</small></article><article><span>👤</span><b id="rEmployees">—</b><small>Employees</small></article><article><span>🏢</span><b id="rHr">—</b><small>HR Accounts</small></article><article><span>📨</span><b id="rApps">—</b><small>Applications Today</small></article><article><span>🟢</span><b id="rHealth">Checking</b><small>Site Health</small></article></div><div class="report-chart"><h3>Traffic — Last 14 Days</h3><div id="trafficBars" class="traffic-bars"><span>Loading...</span></div></div><div class="health-list" id="healthList"></div><div class="repair-row"><button id="seoRepair" class="ok-btn">🔧 Check / Repair SEO</button><button id="siteRefresh" class="block-btn">🔄 Run Site Health Check</button><p id="repairMsg" class="msg"></p></div></section>';$('dashboard').insertBefore(s,$('dashboard').firstElementChild.nextElementSibling);$('refreshReports').onclick=load;$('siteRefresh').onclick=loadHealth;$('seoRepair').onclick=()=>{window.open('https://github.com/junjharsingh2038-png/private-job-alert/actions/workflows/update-seo-job-pages.yml','_blank');$('repairMsg').textContent='SEO workflow opened. Use Run workflow to repair/update SEO pages.'};}
async function auth(){const r=await sb.auth.getSession();if(!r.data?.session)throw Error('Session expired');return r.data.session}
async function count(path,extra='',token=''){const r=await fetch(U+'/rest/v1/'+path+'?select=id'+extra,{headers:{apikey:K,Authorization:'Bearer '+(token||K),'Prefer':'count=exact'},method:'HEAD'});if(!r.ok)throw Error(path+' '+r.status);return Number((r.headers.get('content-range')||'0-0/0').split('/')[1])||0}
function isHr(a){return (a||[]).filter(h=>{const role=String(h?.role||h?.user_metadata?.role||'').toLowerCase();return role==='hr'||role==='employer'||(!['employee','seeker','job_seeker'].includes(role)&&(!!h?.company_name||!!h?.hr_name||!!h?.profile_exists&&!!h?.contact_name))})}
async function loadCounts(){const today=new Date();const iso=today.toISOString().slice(0,10);const day=encodeURIComponent('gte.'+iso+'T00:00:00');const ss=await auth();const [jobs,employees,apps]=await Promise.all([count('jobs','&is_active=eq.true'),count('job_seeker_profiles','',ss.access_token),count('applications','&created_at='+day,ss.access_token)]);$('rJobs').textContent=await count('jobs','&created_at='+day,ss.access_token);$('rEmployees').textContent=employees;$('rApps').textContent=apps;try{const r=await fetch(API,{headers:{Authorization:'Bearer '+ss.access_token,apikey:K}}),d=await r.json();$('rHr').textContent=isHr(d.accounts||[]).length}catch(e){$('rHr').textContent='—'}$('rTraffic').textContent='—';loadTraffic();}
async function loadTraffic(){try{const r=await fetch('data/traffic.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json(),a=(d.views||[]).slice(-14);$('rTraffic').textContent=a.length?(a[a.length-1].count||0):0;$('trafficBars').innerHTML=a.length?a.map(x=>'<div class="traffic-col" title="'+esc(x.date)+': '+esc(xcount(x.count))+'"><i style="height:'+Math.max(8,Math.min(100,(Number(x.count)||0)/(Math.max(...a.map(y=>Number(y.count)||0))||1)*100))+'%"></i><small>'+esc(String(x.date).slice(5))+'</small></div>').join(''):'<span>No traffic data yet.</span>'}catch(e){$('rTraffic').textContent='Not ready';$('trafficBars').innerHTML='<span>Traffic collection is starting. Data will appear after the first scheduled collection.</span>'}}
function xcount(n){return Number(n)||0}
async function loadHealth(){const urls=[['Home Page','index.html'],['Jobs Index','jobs/'],['Sitemap','sitemap.xml'],['HR Portal','hr.html'],['Employee Portal','seeker.html']];const out=[];for(const [name,url] of urls){try{const r=await fetch(url+'?health='+Date.now(),{cache:'no-store'});out.push('<div><span class="health-dot '+(r.ok?'good':'bad')+'"></span><b>'+name+'</b><span>'+r.status+' '+(r.ok?'OK':'Issue')+'</span></div>')}catch(e){out.push('<div><span class="health-dot bad"></span><b>'+name+'</b><span>Unavailable</span></div>')}}$('healthList').innerHTML=out.join('');const bad=out.some(x=>x.includes(' bad'));$('rHealth').textContent=bad?'Issue detected':'All systems OK';$('rHealth').style.color=bad?'#c62828':'#087a36'}
async function load(){try{$('repairMsg').textContent='Refreshing reports...';await loadCounts();await loadHealth();$('repairMsg').textContent='Reports updated.'}catch(e){$('repairMsg').textContent=e.message||'Could not load reports.'}}function init(){if(!$('dashboard'))return;box();load()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();