(function(){'use strict';if(window.__PJA_AUTH_GUARD__)return;window.__PJA_AUTH_GUARD__=1;
const IDLE_MS=5*60*1000,KEY='pja_last_activity_v3',URL='https://rlidcatrwonemshwzafp.supabase.co',KEYS='sb_publishable_ocJhWyfPg9rVhYROn_Vj0Q_DSSgxeuE',ADMIN='junjharsingh740@gmail.com';
let client=null,expired=false;
function path(){return location.pathname.split('/').pop().toLowerCase()}
function db(){if(client)return client;if(window.sb?.auth)return window.sb;if(window.supabase?.createClient)client=window.supabase.createClient(URL,KEYS);return client}
function loadPasswordReset(){if(!['hr.html','seeker.html','admin.html'].includes(path()))return;if(document.querySelector('script[data-pja-password-reset]'))return;const s=document.createElement('script');s.src='password-reset-otp.js?v=20260904';s.dataset.pjaPasswordReset='1';document.body.appendChild(s)}
async function guard(){const s=db();if(!s?.auth)return;const r=await s.auth.getUser(),u=r.data?.user;if(!u)return;const p=path(),email=(u.email||'').toLowerCase(),role=String(u.user_metadata?.role||'').toLowerCase(),md=u.user_metadata||{};let employee=role==='employee',hr=role==='hr'||role==='employer'||(!employee&&(!!md.hr_name||!!md.company)),admin=email===ADMIN;try{if(!employee&&!hr&&!admin){const j=await s.from('jobs').select('id').eq('hr_user_id',u.id).limit(1);hr=!j.error&&(j.data||[]).length>0}}catch(e){}if(p==='admin.html'&&!admin){await s.auth.signOut();alert('Admin access denied.');location.reload();return}if(p==='hr.html'&&employee){await s.auth.signOut();alert('This Employee Login ID cannot access the HR Portal.');location.reload();return}if(p==='seeker.html'&&hr&&!admin){await s.auth.signOut();alert('This HR Login ID cannot access the Employee Portal.');location.reload();return}}
function touch(){localStorage.setItem(KEY,String(Date.now()))}
async function idle(){const s=db();if(!s?.auth||expired)return;const r=await s.auth.getUser();if(!r.data?.user)return;const last=Number(localStorage.getItem(KEY)||Date.now());if(Date.now()-last>=IDLE_MS){expired=true;localStorage.removeItem(KEY);await s.auth.signOut();alert('Your session expired after 5 minutes of inactivity. Please login again.');location.reload()}}
function start(){if(!db()?.auth)return;const p=path();if(!['hr.html','seeker.html','admin.html'].includes(p))return;loadPasswordReset();const old=Number(localStorage.getItem(KEY));if(!old||Date.now()-old>IDLE_MS)localStorage.setItem(KEY,String(Date.now()));['click','keydown','pointerdown','scroll','touchstart'].forEach(x=>window.addEventListener(x,touch,{passive:true}));setInterval(idle,10000);setTimeout(guard,100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
