(function(){'use strict';
function slug(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'job'}
function makeUrl(j){return location.origin+'/private-job-alert/jobs/'+slug(j.title)+'-'+slug(j.company||j.company_name)+'-'+String(j.id||'').slice(0,8)+'/'}
function getJob(card){const b=card.querySelector('.apply[onclick]');if(!b)return null;const s=b.getAttribute('onclick')||'',a=s.indexOf('openApply('),z=s.lastIndexOf(')');if(a<0||z<0)return null;try{return JSON.parse(s.slice(a+10,z).replace(/&#39;/g,"'"))}catch(e){return null}}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
async function copy(url){try{await navigator.clipboard.writeText(url);return true}catch(e){try{const t=document.createElement('textarea');t.value=url;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();return true}catch(x){return false}}}
function share(j){const url=makeUrl(j),title=j.title||'Private Job',company=j.company||j.company_name||'',text=title+(company?' | '+company:'')+' | Private Job Alert',q=encodeURIComponent(text+'\n'+url),u=encodeURIComponent(url),logo=window.PJACompanyLogo?.make?window.PJACompanyLogo.make(company):'<div class="pja-share-icon">↗</div>';if(typeof openModal==='function'){openModal('<div class="pja-share-modal"><button class="pja-share-close" onclick="closeModal()">×</button><div class="pja-share-head">'+logo+'<div><h2>Share Job</h2><p>Share this vacancy with candidates</p></div></div><div class="pja-share-job"><strong>'+esc(title)+'</strong><span>'+esc(company)+'</span></div><div class="pja-share-options"><button class="pja-share-option whatsapp" onclick="PJAJobShare.open(\'https://wa.me/?text='+q+'\')"><b>WhatsApp</b><small>Share with contacts or groups</small></button><button class="pja-share-option telegram" onclick="PJAJobShare.open(\'https://t.me/share/url?url='+u+'&text='+encodeURIComponent(text)+'\')"><b>Telegram</b><small>Share in channels or groups</small></button><button class="pja-share-option facebook" onclick="PJAJobShare.open(\'https://www.facebook.com/sharer/sharer.php?u='+u+'\')"><b>Facebook</b><small>Share on Facebook</small></button><button class="pja-share-option copy" onclick="PJAJobShare.copy(\''+url.replace(/'/g,"\\'")+'\',this)"><b>Copy Link</b><small>Copy the job link</small></button></div><div class="pja-share-url">'+esc(url)+'</div></div>');return}copy(url).then(()=>alert('Job link copied.'))}
function open(url){window.open(url,'_blank','noopener,noreferrer')}
async function copyBtn(url,b){const ok=await copy(url),old=b.querySelector('b').textContent;b.querySelector('b').textContent=ok?'✓ Link Copied':'Copy Link';setTimeout(()=>b.querySelector('b').textContent=old,1800)}
function wire(card){const j=getJob(card);if(!j||!j.id)return;card.querySelectorAll('[data-job-share]').forEach(b=>{if(b.dataset.shareWired)return;b.dataset.shareWired='1';b.onclick=e=>{e.preventDefault();e.stopPropagation();share(j)}});card.querySelectorAll('[data-job-copy]').forEach(b=>{if(b.dataset.copyWired)return;b.dataset.copyWired='1';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const ok=await copy(makeUrl(j));const old=b.textContent;b.textContent=ok?'✓ Copied':'Copy Link';setTimeout(()=>b.textContent=old,1400)}})}
function add(){document.querySelectorAll('.nk-job-card,.job').forEach(wire)}
window.PJAJobShare={share,add,makeUrl,open,copy:copyBtn};function start(){add();setTimeout(add,300);setTimeout(add,1000);setTimeout(add,2500);new MutationObserver(add).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();